import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';

const PrivacyPolicy = () => {
  const [currentDate, setCurrentDate] = useState('');

  useEffect(() => {
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    setCurrentDate(new Date().toLocaleDateString('en-US', options));
  }, []);

  return (
    <div className="privacy-container">
      
      <div className="privacy-content">
        <h1 className="title-bordered">Privacy Policy</h1>
        <p><strong>Effective Date:</strong> <span className="date-text">{currentDate}</span></p>

        <p>Thank you for choosing to use our <strong>204Eight</strong> application ("App"). We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains what information we collect, how we use it, and what rights you have in relation to it.</p>
        
        <p>The 204Eight app is provided at no cost and is intended for use as is.</p>

        <section className="policy-section">
          <h2>1. Information We Collect</h2>
          <p>We believe in data minimization. <span className="highlight">We do not collect, store, share, or transmit any of your personal information.</span> Everything you do in the game stays strictly on your device.</p>
          <p>Any data generated by the game, such as your high scores or saved game progress, is stored locally on your device's internal storage and is never transmitted to our servers or any third-party servers.</p>
        </section>

        <section className="policy-section">
          <h2>2. App Permissions</h2>
          <p>To provide our core functionality, the App may require certain default device permissions. We use these permissions solely for the operation of the App:</p>
          <ul>
            <li><strong>Vibration / Haptic Feedback (Optional):</strong> The app may use your device's vibration capabilities to provide haptic feedback when you merge tiles, enhancing your gameplay experience. These permissions are strictly used for the core functionality of the game on your device and are never used to access, collect, or monitor your personal data.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>3. Third-Party Services</h2>
          <p>The App does not integrate any third-party analytics, tracking, or ad-serving frameworks that collect your personal information. We do not share your data with advertisers or marketing companies.</p>
        </section>

        <section className="policy-section">
          <h2>4. Log Data</h2>
          <p>We do not collect any Log Data or crash reports. If the app crashes, no diagnostic data is sent to us or any third parties.</p>
        </section>

        <section className="policy-section">
          <h2>5. Children’s Privacy</h2>
          <p>Our Service does not collect any personal identifiable information from anyone, including children under the age of 13. If you are a parent or guardian and you have concerns about the app, please contact us.</p>
        </section>

        <section className="policy-section">
          <h2>6. Changes to This Privacy Policy</h2>
          <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>
        </section>

        <div className="contact-info glass-panel">
            <h2>7. Contact Us</h2>
            <p>If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at:</p>
            <p><strong>Email: </strong><a href="mailto:prakash.jha9797@gmail.com" className="email-link">prakash.jha9797@gmail.com</a></p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
